CREATE TYPE "public"."playlist_audience" AS ENUM('creator', 'boutique');--> statement-breakpoint
-- Drizzle generated this CREATE TABLE because newsletter_subscribers was added to the schema without a prior migration.
-- Wrapped in IF NOT EXISTS to stay idempotent: no-op if the table was already pushed via drizzle-kit push, creates it otherwise.
CREATE TABLE IF NOT EXISTS "newsletter_subscribers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"locale" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "newsletter_subscribers_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "playlist_tracks" ADD COLUMN "is_demo" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "playlists" ADD COLUMN "audience" "playlist_audience" DEFAULT 'creator' NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "playlist_tracks_one_demo_per_playlist" ON "playlist_tracks" USING btree ("playlist_id") WHERE "playlist_tracks"."is_demo" = true;--> statement-breakpoint
-- Seed: 7 boutique playlists (vertical-specific, empty at deploy, Emil curates manually after)
INSERT INTO "playlists" ("slug", "name_fr", "name_en", "description_fr", "description_en", "gradient", "emoji", "audience", "is_published", "display_order") VALUES
  ('salon-coiffure', 'Salon de coiffure', 'Hair Salon', 'Musique pour salon de coiffure libre de droits, pensée pour rythmer vos journées sans lasser vos clients ni votre équipe. Une sélection tendance et énergique modérée, qui s''intègre naturellement à l''ambiance d''un salon professionnel. Diffusion publique 100% en règle, sans déclaration SACEM ni redevance annexe.', 'Royalty-free music for hair salons, designed to keep the energy fresh throughout the day without tiring your clients or your team. A modern, moderately upbeat selection that blends naturally into a professional salon atmosphere. Public broadcasting fully covered, no rights organisation required.', 'linear-gradient(135deg, #f5a623 0%, #d97706 100%)', '💇', 'boutique', true, 1),
  ('institut-beaute', 'Institut de beauté & onglerie', 'Beauty Salon & Nail Bar', 'Musique pour institut de beauté libre de droits, douce et féminine élégante pour accompagner vos soins esthétiques et prestations onglerie. Une ambiance raffinée qui valorise l''expérience cliente et installe un climat de bien-être dès l''accueil. Conforme à la diffusion publique en établissement.', 'Royalty-free music for beauty salons, soft and elegantly feminine to accompany aesthetic treatments and nail services. A refined atmosphere that elevates the client experience and creates a sense of wellbeing from the moment they walk in. Public broadcasting compliant.', 'linear-gradient(135deg, #ec4899 0%, #a855f7 100%)', '💅', 'boutique', true, 2),
  ('spa-massage', 'Spa & massage', 'Spa & Massage', 'Musique pour spa libre de droits, zen et méditative pour accompagner massages, soins et parcours de relaxation. Une sélection apaisante qui prolonge le voyage sensoriel de vos clients et installe une bulle hors du temps. Licence diffusion publique incluse, sans redevance SACEM.', 'Royalty-free music for spas, zen and meditative to accompany massages, treatments and relaxation rituals. A soothing selection that extends your clients'' sensory journey and creates a timeless escape. Public broadcasting licence included, no rights royalties.', 'linear-gradient(135deg, #14b8a6 0%, #0e7490 100%)', '🧘', 'boutique', true, 3),
  ('cabinet-veterinaire', 'Cabinet vétérinaire', 'Veterinary Clinic', 'Musique pour cabinet vétérinaire libre de droits, spécifiquement choisie pour apaiser les animaux et rassurer leurs propriétaires en salle d''attente comme en consultation. Tempo lent, fréquences douces, instruments non-agressifs : une ambiance pensée pour réduire le stress avant l''examen.', 'Royalty-free music for veterinary clinics, specifically curated to calm animals and reassure their owners — both in the waiting room and during consultations. Slow tempo, gentle frequencies and non-aggressive instruments combine to reduce stress before the exam.', 'linear-gradient(135deg, #65a30d 0%, #4d7c0f 100%)', '🐾', 'boutique', true, 4),
  ('cabinet-dentaire', 'Cabinet dentaire', 'Dental Practice', 'Musique pour cabinet dentaire libre de droits, apaisante et rassurante pour atténuer l''anxiété de vos patients en salle d''attente et pendant les soins. Une sélection neutre, jamais intrusive, qui couvre les bruits techniques sans ajouter de tension. Diffusion publique en règle.', 'Royalty-free music for dental practices, calming and reassuring to ease patient anxiety in the waiting room and during treatments. A neutral, never intrusive selection that masks technical noises without adding tension. Public broadcasting compliant.', 'linear-gradient(135deg, #38bdf8 0%, #0284c7 100%)', '🦷', 'boutique', true, 5),
  ('osteopathe-kine', 'Ostéopathe & kiné', 'Osteopathy & Physiotherapy', 'Musique pour cabinet d''ostéopathie et kinésithérapie libre de droits, propice à la détente profonde et à la concentration du praticien comme du patient. Tempo régulier, ambiance enveloppante, idéale pour les séances de manipulation, de rééducation et d''étirements.', 'Royalty-free music for osteopathy and physiotherapy practices, supporting deep relaxation and the focus of both practitioner and patient. Steady tempo, enveloping atmosphere — ideal for manipulation sessions, rehabilitation and stretching work.', 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)', '🤲', 'boutique', true, 6),
  ('cabinet-psychologue', 'Cabinet de psychologue', 'Therapy & Psychology Practice', 'Musique pour cabinet de psychologue libre de droits, neutre et bienveillante pour accompagner vos consultations et apaiser la salle d''attente. Une sélection sans paroles, sans charge émotionnelle marquée, qui crée un sas de transition rassurant entre le quotidien et la séance.', 'Royalty-free music for therapy and psychology practices, neutral and gentle to accompany consultations and soothe the waiting area. A wordless, emotionally neutral selection that creates a reassuring transition space between daily life and the session.', 'linear-gradient(135deg, #64748b 0%, #334155 100%)', '🧠', 'boutique', true, 7)
ON CONFLICT ("slug") DO NOTHING;